# Generated by Django 4.2.8 on 2024-02-27 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0136_export_path"),
        ("ussd", "0002_alter_handler_aggregator"),
    ]

    operations = [
        migrations.AddField(
            model_name="handler",
            name="org_id",
            field=models.ForeignKey(
                default=1,
                help_text="The organization associated with this USSD handler",
                on_delete=django.db.models.deletion.CASCADE,
                to="orgs.org",
                verbose_name="Organization",
            ),
        ),
    ]
